Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	vcf_gds
	1

[Mon Mar  4 12:29:06 2019]
rule vcf_gds:
    input: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_chr22_4PCA.vcf.gz, /home/kgoldmann/Documents/PEAC_eqtl/Data/RP/ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz
    output: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_PCA.gds, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_PCA.gds
    jobid: 0

[Mon Mar  4 12:29:07 2019]
Error in rule vcf_gds:
    jobid: 0
    output: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_PCA.gds, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_PCA.gds

RuleException:
CalledProcessError in line 290 of /home/kgoldmann/Documents/Git/peac/Snakefile:
Command ' set -euo pipefail;  Rscript --vanilla /home/kgoldmann/Documents/Git/peac/.snakemake/scripts/tmp9isd3316.vcf_PCA2gds.R ' returned non-zero exit status 1.
  File "/home/kgoldmann/Documents/Git/peac/Snakefile", line 290, in __rule_vcf_gds
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kgoldmann/Documents/Git/peac/.snakemake/log/2019-03-04T122906.628738.snakemake.log
